export type TGranularity =
  | 'all'
  | 'none'
  | 'second'
  | 'minute'
  | 'five_minute'
  | 'ten_minute'
  | 'fifteen_minute'
  | 'thirty_minute'
  | 'hour'
  | 'six_hour'
  | 'eight_hour'
  | 'day'
  | 'week'
  | 'month'
  | 'quarter'
  | 'year';
